### PR TITLE
Fix relative links

### PR DESCRIPTION
**Pull request by therobinkim**

### CODE REVIEW

**Comment by therobinkim** [comment]
For reference, below is a screenshot of the file/directory structure as shown by my Octotree Chrome extension. The `index.md` file, which this PR affects, has been highlighted for visual clarity.

image

**Comment by bebraw** [comment]
You should skip the `.md` suffixes as those won't be in the generated result. The basic idea is fine.

**Comment by therobinkim** [comment]
@bebraw Understood! I dropped the `.md` suffixes and resolved merge conflicts from the other PR that was merged before this one.

**Comment by therobinkim** [comment]
Actually, closing my PR because I was stupid and never ran the app locally! My proposals break something that already works. Whoops!

**Pull request closed without merging**
