### PR TITLE
Styling and Layout

### PR DESCRIPTION
**Pull request by gregvenech**
This PR contains:

- Merged layouts and components
- Some new components and updates to existing ones
- Cleaned up styling,  and a base styling for markdown
- Consistent font sizing using modular scale (continued)

I was going to push this further before creating a PR but I realized the branches are starting to diverge, already seeing a few conflicts, so I think it's best to get it in sooner rather than later...

I'll work on resolving the conflicts tonight.

### CODE REVIEW

**Comment by bebraw** [comment]
Ok, let's merge once the conflicts have been resolved (probably a couple of places by the looks of it). 👍

**Comment by bebraw** [comment]
Btw, feel free to rebase (`git rebase -i develop`) and force push (`git push --force`) in feature branches in the future. Probably easier to resolve possible conflicts.

**Comment by gregvenech** [comment]
The way I have this branch set up, we'd probably need an index.md for each section giving a basic description of what it contains... if this doesn't work we can go back to the SectionPage/SectionIndex setup.

**Comment by bebraw** [comment]
Merged. Looking good. 👍 

> The way I have this branch set up, we'd probably need an index.md for each section giving a basic description of what it contains... if this doesn't work we can go back to the SectionPage/SectionIndex setup.

What if I expanded Antwar so that it would pick up `concepts/index.md` etc. ? We could write introductions there. Would that work?

**Comment by gregvenech** [comment]
> What if I expanded Antwar so that it would pick up concepts/index.md etc. ? We could write introductions there. Would that work?

@bebraw that's exactly what I was thinking, would be perfect if it's not a hassle.

**Comment by bebraw** [comment]
Ok, I'll give it a go then.

**Comment by bebraw** [comment]
@gregvenech Done. It should pick up `index.md` per section after `npm update` now.

**Pull request merged**
